### ISSUE TITLE
Fail to install Copper using rubygems

### ISSUE THREAD

**Issue by superbrothers** [cloud66/copper#4]
I tried to install Copper with the following steps, but actually another copper (https://rubygems.org/gems/copper) was installed. Looks like it is not yours.

> Copper is available as a Ruby gem. We recommend installing Copper using Rubygems.
> 
> To install Copper, use the following command:
> 
> $ gem install copper
> 
> You should now be able to run $ copper version successfully.

https://copper.sh/docs/getting-started/

**Comment by superbrothers** [comment]
I created a Docker image for Copper. This is an easy way to use Copper. Thanks. https://github.com/superbrothers/copper-docker

**Comment by khash** [comment]
There was a mixup in the gem name between Rubygem and our own private gem repository prior to making Copper public. This is now resolved and the gem itself is now called `c66-copper`. Apologies for this mixup.

**Comment by khash** [comment]
Thank you for the docker image!
